### ISSUE TITLE
Implementation of 'Guest' Dashboard

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/lab-data-service-dashboard#10]
Guest will be able to view the labs and  users data available in the system.

**Comment by obliviateandsurrender** [comment]
Guest dashboard with basic CRUD functionality assigned to him is ready. Lab integration is now left along with the styling.

**Comment by obliviateandsurrender** [comment]
The CRUD operations are ready for Admin is done and all routes have been tested. Thing left is now is styling and lab-data-service routes integration.
[Get JSON](https://github.com/vlead/lab-data-service-dashboard/blob/master/src/runtime/rest/web-frontend.org#get-json)
[guest_dash & guest_nav](https://github.com/vlead/lab-data-service-dashboard/blob/master/src/runtime/rest/web-frontend.org#user-and-role-specifications)
