### ISSUE TITLE
First Review Comments [09-06-2017]

### ISSUE THREAD

**Issue by obliviateandsurrender** [vlead/lab-data-service-dashboard#13]
1. Look for possibility of better implementation
    * ~~Think about simpler and powerful Angular JS/Swagger/Jinja implementation instead of simple JavaScript.~~ 
    * ~~Try to use Django framework instead of Flask.~~
2. REST APIs Documentation
    * ~~Remove the arguments from the URLs in the POST and PUT method, in our Rest APIs documentation.~~
    * Verbose error codes for the REST APIs.
3. Incompatibility with coding convention
    * ~~All the API method calls needs to be checked for the type of method allowed and call that was given.~~

**Comment by madhavipuliraju** [comment]
2. REST APIs Documentation
- Remove the arguments from the URLs in the POST and PUT method, in our Rest APIs documentation.
  DONE
