### ISSUE TITLE
Read Json elements and generate html code 

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/lab-data-service-dashboard#15]
Read Json elements and generate html code

**Comment by obliviateandsurrender** [comment]
I fixed a bug regarding discarding of classes and on-click information when the JSON data was imported and read by the functions.
https://github.com/vlead/lab-data-service-dashboard/blob/web-app/src/runtime/rest/web-frontend.org#docoding-a-json

**Comment by obliviateandsurrender** [comment]
Done.
[Get JSON](https://github.com/vlead/lab-data-service-dashboard/blob/master/src/runtime/rest/web-frontend.org#get-json)
[Generating HTML code](https://github.com/vlead/lab-data-service-dashboard/blob/master/src/runtime/rest/web-frontend.org#docoding-a-json)
