### ISSUE TITLE
Implement Event handlers for all CRUD operations in front end

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/lab-data-service-dashboard#16]
Implement Event handlers for all CRUD operations in front end

**Comment by obliviateandsurrender** [comment]
I am currently stuck with a issue that has to do with discarding of Event Listener attached to a DOM element when it is deleted. When I delete the buttons the events listeners attached to it must be deleted but in my case the listeners are persisting.
[Following this discussion](https://stackoverflow.com/questions/12528049/if-a-dom-element-is-removed-are-its-listeners-also-removed-from-memory)

**Comment by obliviateandsurrender** [comment]
The listener remained attached on the document layer and thus just removing the button wasn't removing the listener. Basically .on() on document was leading to bubbling.
[.on()](http://api.jquery.com/on/)
[Bubbling](https://javascript.info/bubbling-and-capturing)
