### ISSUE TITLE
Creation of JSON specifications to define the HTML Structure for generation of 'Role' and 'User' entities

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/lab-data-service-dashboard#17]
Creation of JSON specifications to define the HTML Structure for generation of 'Role' and 'User' entities. All the CRUD operations of 'Admin' and 'Guest' dashboards will be auto generated with the help of these JSON Specifications.

**Comment by Yahnit** [comment]
https://github.com/vlead/lab-data-service-dashboard/blob/web-app/src/runtime/rest/web-frontend.org#user-and-role-specifications
