### ISSUE TITLE
Code Review Comments [30-06-2017]

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/lab-data-service-dashboard#20]
- lab data service can be renamed as experiment as service
- Try with no sql database like mongodb for lds instead of RDBMS. [#65](https://github.com/vlead/lab-data-service/issues/65)
- Given a role, all the permissions of that role need to be mentioned.
eg: Admin can Create, Read, Update and Delete
- when a person with cse department logged in he need not to see the
  other department details.
- literate style need to be followed strictly 
- why not django? design decisions need to be documented.
- In Single Page Applications(SPA), searching feature may have a problem because it might not have indexing.
- Why SPA? Pros and Cons need to be documented.

**Comment by obliviateandsurrender** [comment]
For the third thing should be use a user-role database? 
Example [Permission Management](https://stackoverflow.com/questions/199252/what-is-the-best-way-to-manage-permissions-for-a-web-application-bitmask-or-da)
