### ISSUE TITLE
Need DNS entry for a container on base4

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/lab-data-service-dashboard#28]
@vlead/systems  

We have deployed lab-data-service-dashboard project manually on base4 to fix the login issue with google oauth. Hence we need DNS entry for the following container.

IP: http://10.4.14.237/
DNS: http://lds-dashboard.vlabs.ac.in/

**Comment by kraghupathi** [comment]
@madhavipuliraju : Please follow the DNS entry for [http://lds-dashboard-base4.vlabs.ac.in/](http://lds-dashboard-base4.vlabs.ac.in/)

**Comment by madhavipuliraju** [comment]
@kraghupathi  
thanks
