### ISSUE TITLE
Ensure the application runs in user development environment

### ISSUE THREAD

**Issue by travula** [vlead/lab-data-service-dashboard#38]
The application should run in user development environment.

**Comment by madhavipuliraju** [comment]
Documentation to run lds dashboard on development environment: [link](https://github.com/vlead/lab-data-service-dashboard/blob/refactor/src/imp/deployment/run-lds-dashboard-in-development-environment.org)
Commit id: [62197302df48a7bfef28780bfa5be0ee5c7fb955](62197302df48a7bfef28780bfa5be0ee5c7fb955)
