### ISSUE TITLE
Implement the unit test cases for login, logout, users and roles  

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/lab-data-service-dashboard#4]
Implement the unit test cases for login, logout, users and roles

**Comment by obliviateandsurrender** [comment]
https://github.com/vlead/lab-data-service-dashboard/blob/develop/src/imp/runtime/rest/api.org#test-cases
https://github.com/vlead/lab-data-service-dashboard/blob/develop/src/imp/runtime/rest/api.org#tests
