### ISSUE TITLE
Integration of google authentication with login and logout API's

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/lab-data-service-dashboard#5]
Integration of google authentication with login and logout API's

**Comment by obliviateandsurrender** [comment]
https://github.com/vlead/lab-data-service-dashboard/blob/develop/src/imp/runtime/rest/api.org#login-api
https://github.com/vlead/lab-data-service-dashboard/blob/develop/src/imp/runtime/rest/api.org#logout-api
