### ISSUE TITLE
Implementation of Admin Dashboard

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/lab-data-service-dashboard#9]
Implementation of Admin Dashboard.
Admin will be able to perfrom the following operations:
1) Add User
2) Update User
3) Delete User
4) Assign Role to a User
5) View all Users

**Comment by obliviateandsurrender** [comment]
The CRUD operations are ready for Admin is done and all routes have been tested. Thing left is now is styling and lab-data-service routes integration.
[Get JSON](https://github.com/vlead/lab-data-service-dashboard/blob/master/src/runtime/rest/web-frontend.org#get-json)
[admin_dash & admin_nav](https://github.com/vlead/lab-data-service-dashboard/blob/master/src/runtime/rest/web-frontend.org#user-and-role-specifications)
